services:

  backend:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
      - "5000:5000"
    depends_on:
      - db
    restart: always
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - remind

  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./server/db_data:/var/lib/postgresql/data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - remind

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - remind

networks:
  remind:
    driver: bridge