services:
  frontend:
    build:
      context: ./client
    volumes:
      - ./client/dist:/usr/share/nginx/html
    ports:
      - "8080:80"

  backend:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
      - "5000:5000"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./server/db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
